// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        agp_version = '9.2.0'
        kotlin_version = '2.3.0'
        coroutine_version = '1.8.1'
        amplify_version = '2.29.2'
        aws_version = '2.81.0'
        dokka_version = '2.0.0'
    }

    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        if (project.file("${rootProject.projectDir}/util/license-tools.gradle").exists() &&
                project.hasProperty("nexusUsername") &&
                project.hasProperty("nexusPassword")) {
            maven {
                url = uri("https://repo.tools.anonyome.com/repository/android-releases")
                credentials {
                    username = project.property("nexusUsername").toString()
                    password = project.property("nexusPassword").toString()
                }
                content {
                    includeGroup("com.anonyome")
                }
            }
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:$dokka_version"
        classpath "org.jmailen.gradle:kotlinter-gradle:5.4.2"
        if (project.file("${rootProject.projectDir}/util/license-tools.gradle").exists()) {
            classpath "com.anonyome:license-tools:4.0.0"
        }
        if (project.file("${rootProject.projectDir}/util/vulnerability-scan.gradle").exists()) {
            classpath "org.owasp:dependency-check-gradle:12.2.2"
        }
        if (project.file("${rootProject.projectDir}/util/sonarqube.gradle").exists()) {
            classpath "org.sonarqube:org.sonarqube.gradle.plugin:7.5.0.8588"
        }
        classpath ("com.squareup.moshi:moshi") {
            version{
                strictly '1.8.0'
            }
        }
    }
}

plugins {
    id "io.github.gradle-nexus.publish-plugin" version "1.1.0"
    id "com.github.ben-manes.versions" version "0.39.0"
    id "com.apollographql.apollo" version "4.3.3"
}

ext {
    projectGroup = 'com.sudoplatform'
}

if(project.file("${rootProject.projectDir}/util/internal-repo.gradle").exists()) {
    apply from: "${rootProject.projectDir}/util/internal-repo.gradle"
}
else {
    ext["internalRepoUsername"] = ""
    ext["internalRepoPassword"] = ""
    ext["internalSnapshotRepoUrl"] = ""
    ext["internalSnapshotRepoName"] = ""
    ext["internalReleaseRepoUrl"] = ""
    ext["internalReleaseRepoName"] = ""
    ext["sonatypeStagingProfileId"] = ""
}

if (project.findProperty("tag") && sonatypeStagingProfileId) {
    nexusPublishing {
        repositories {
            sonatype {
                nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
                stagingProfileId = sonatypeStagingProfileId

                username = nexusUsername
                password = nexusPassword
            }
        }
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        if (internalRepoUsername?.trim()) {
            maven {
                name = internalSnapshotRepoName
                url = internalSnapshotRepoUrl
                credentials {
                    username = internalRepoUsername
                    password = internalRepoPassword
                }
            }
            maven {
                name = internalReleaseRepoName
                url = internalReleaseRepoUrl
                credentials {
                    username = internalRepoUsername
                    password = internalRepoPassword
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}

// Check outdated dependencies with suppressions
if (project.file("${rootProject.projectDir}/util/outdated-with-suppressions.gradle").exists()) {
    apply from: "${rootProject.projectDir}/util/outdated-with-suppressions.gradle"
}